# /// script
# dependencies = ["Jinja2==3.1.6", "PyYAML==6.0.3"]
# ///
"""Build portable HTML from language-specific lessons and shared presentation."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import tempfile
from html.parser import HTMLParser

from jinja2 import DictLoader, Environment, StrictUndefined, TemplateError, select_autoescape
import yaml

ROOT = Path(__file__).resolve().parent
MARKER = re.compile(r'\A<!DOCTYPE html>\n<!-- Generated by build.py; sha256=([a-f0-9]{64}); edit content/ and shared/\. -->\n')
LESSON_NAME = re.compile(r'aula-(0|[1-9]\d*)-([1-9]\d*)\.html')
SOURCE_TYPES = {'.html', '.css', '.js', '.yaml', '.json'}


def require(condition, message):
    if not condition:
        raise ValueError(message)


def digest(data):
    return hashlib.sha256(data).hexdigest()


class UniqueLoader(yaml.SafeLoader):
    """Do not silently discard duplicate metadata keys."""


def unique_mapping(loader, node, deep=False):
    keys = [loader.construct_object(key, deep=deep) for key, _ in node.value]
    require(all(isinstance(key, str) for key in keys), 'Metadata keys must be strings')
    require(len(keys) == len(set(keys)), f'Duplicate metadata key near line {node.start_mark.line + 1}')
    return yaml.SafeLoader.construct_mapping(loader, node, deep)


UniqueLoader.add_constructor(yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, unique_mapping)


def metadata(text, required, optional, context):
    data = yaml.load(text, Loader=UniqueLoader)
    require(isinstance(data, dict), f'{context}: expected a mapping')
    require(required <= data.keys(), f'{context}: missing {sorted(required - data.keys())}')
    require(data.keys() <= required | optional, f'{context}: unknown fields {sorted(data.keys() - required - optional)}')
    return data


def text_fields(data, fields, context):
    for key in fields:
        require(isinstance(data.get(key), str) and data[key].strip(), f'{context}: {key} must be nonempty text')


def read_sources(root):
    return {p.relative_to(root).as_posix(): p.read_text()
            for folder in ('shared', 'content') for p in sorted((root / folder).rglob('*'))
            if p.is_file() and p.suffix in SOURCE_TYPES and not p.name.startswith('.')}


def load_lesson(name, text):
    match = LESSON_NAME.fullmatch(Path(name).name)
    require(match is not None, f'Invalid lesson filename: {name}')
    header = re.match(r'\A---\n(.*?)\n---\n', text, re.S)
    require(header is not None, f'{name}: YAML frontmatter is required')
    required = {'title', 'map_title', 'summary'}
    optional = {'short_title', 'description'}
    lesson = metadata(header[1], required, optional, name)
    text_fields(lesson, required | (lesson.keys() & optional), name)
    module, number = match.groups()
    return dict(lesson, id=Path(name).stem, module=module, number=f'{module}.{number}',
                order=int(number), short_title=lesson.get('short_title', lesson['title']),
                description=lesson.get('description'), body=text[header.end():])


class DocumentLinks(HTMLParser):
    def __init__(self, html):
        super().__init__(convert_charrefs=True)
        self.ids, self.references = set(), set()
        self.feed(html)
        self.close()
        require(self.references <= self.ids, f'Broken local links: {sorted(self.references - self.ids)}')

    def handle_starttag(self, tag, attributes):
        attrs = dict(attributes)
        if 'id' in attrs:
            require(attrs['id'] not in self.ids, f'Duplicate HTML id: {attrs["id"]}')
            self.ids.add(attrs['id'])
        if attrs.get('href', '').startswith('#') and len(attrs['href']) > 1:
            self.references.add(attrs['href'][1:])
        for key in ('data-answer', 'data-question', 'data-validator', 'aria-controls', 'aria-labelledby', 'aria-describedby'):
            self.references.update((attrs.get(key) or '').split())

    handle_startendtag = handle_starttag


def book_config(language, sources):
    prefix = f'content/{language}/'
    require(prefix + 'book.yaml' in sources, f'No book configured for {language}')
    book = metadata(sources[prefix + 'book.yaml'], {'language', 'title', 'output', 'modules'}, set(), prefix)
    text_fields(book, {'language', 'title', 'output'}, prefix)
    require(book['language'] == language, f'{prefix}: language must match its directory')
    require(re.fullmatch(r'[A-Za-z][A-Za-z0-9-]*\.html', book['output']), 'Output must be a root-level HTML filename')
    require(isinstance(book['modules'], list) and book['modules'], f'{prefix}: modules must be a nonempty list')
    return book


def language_choices(language, sources, outputs):
    labels = {'pt-BR': ('PT', 'Português (Brasil)'), 'en': ('EN', 'English')}
    choices = []
    for locale in list(labels) + sorted(set(outputs) - set(labels)):
        label, name = labels.get(locale, (locale, locale))
        anchors = []
        output = outputs.get(locale)
        if output:
            target = book_config(locale, sources)
            require(output == target['output'], f'Language destination differs from its book: {locale}')
            anchors = ['capa', 'sumario']
            for module in target['modules']:
                anchors.extend([f'modulo-{module["id"]}', f'referencias-modulo-{module["id"]}'])
            anchors.extend(Path(path).stem for path in sources
                           if path.startswith(f'content/{locale}/aula-') and path.endswith('.html'))
        choices.append(dict(language=locale, label=label, name=name, output=output,
                            selected=locale == language, anchors=anchors))
    return choices


def render_book(language, sources, language_outputs=None):
    prefix = f'content/{language}/'
    book = book_config(language, sources)
    lessons = [load_lesson(name, text) for name, text in sources.items()
               if name.startswith(prefix + 'aula-') and name.endswith('.html')]
    require(lessons, f'{prefix}: no lessons found')
    module_ids = set()
    for module in book['modules']:
        require(isinstance(module, dict) and set(module) == {'id', 'title', 'summary'}, f'{prefix}: invalid module fields')
        text_fields(module, {'title', 'summary'}, prefix)
        module['id'] = str(module['id'])
        require(re.fullmatch(r'0|[1-9]\d*', module['id']), f'{prefix}: invalid module id')
        require(module['id'] not in module_ids, f'{prefix}: duplicate module {module["id"]}')
        module_ids.add(module['id'])
        module['lessons'] = sorted((x for x in lessons if x['module'] == module['id']), key=lambda x: x['order'])
        require(module['lessons'], f'{prefix}: module {module["id"]} has no lessons')
        module['references'] = sources[prefix + f'references-{module["id"]}.html']
    require(all(x['module'] in module_ids for x in lessons), f'{prefix}: lesson belongs to an unconfigured module')
    expected = {'book.yaml', 'intro.html', 'ui.json'} | {f'{x["id"]}.html' for x in lessons} | {f'references-{m}.html' for m in module_ids}
    actual = {name.removeprefix(prefix) for name in sources if name.startswith(prefix)}
    require(actual == expected, f'{prefix}: missing {sorted(expected - actual)}; unused {sorted(actual - expected)}')

    templates = {name.removeprefix('shared/'): value for name, value in sources.items() if name.startswith('shared/')}
    templates['intro.html'] = sources[prefix + 'intro.html']
    i18n = json.loads(sources[prefix + 'ui.json'])
    required_keys = set(re.findall(r'\bi18n\.([A-Za-z]\w*)', '\n'.join(templates.values())))
    require(isinstance(i18n, dict), f'{prefix}ui.json: expected an object')
    require(set(i18n) == required_keys,
            f'{prefix}ui.json: keys must match shared UI; missing {sorted(required_keys - set(i18n))}; extra {sorted(set(i18n) - required_keys)}')
    text_fields(i18n, required_keys, prefix + 'ui.json')
    env = Environment(loader=DictLoader(templates), autoescape=select_autoescape(['html']),
                      undefined=StrictUndefined, keep_trailing_newline=True, trim_blocks=True)
    env.policies['json.dumps_kwargs'] = {'sort_keys': True, 'ensure_ascii': False}
    outputs = language_outputs if language_outputs is not None else {language: book['output']}
    require(outputs.get(language) == book['output'], 'The current language must be available')
    choices = language_choices(language, sources, outputs)
    html = env.get_template('layout.html').render(book=book, i18n=i18n, languages=choices,
                                               styles=templates['styles.css'], app=templates['app.js'])
    DocumentLinks(html)
    require(html.startswith('<!DOCTYPE html>\n'), 'Layout must begin with the HTML doctype')
    marker = f'<!-- Generated by build.py; sha256={digest(html.encode())}; edit content/ and shared/. -->\n'
    html = html.replace('<!DOCTYPE html>\n', '<!DOCTYPE html>\n' + marker, 1)
    return book['output'], html.encode(), len(lessons)


def is_generated(data):
    text = data.decode('utf-8', errors='replace')
    match = MARKER.match(text)
    if not match:
        return False
    original = '<!DOCTYPE html>\n' + text[match.end():]
    return digest(original.encode()) == match[1]


def atomic_write(path, data, previous):
    """Refuse a changed destination instead of silently overwriting concurrent work."""
    with tempfile.NamedTemporaryFile(dir=path.parent, prefix='.' + path.name + '-', delete=False) as file:
        temporary = Path(file.name)
        file.write(data)
        file.flush()
        os.fsync(file.fileno())
    try:
        require((path.read_bytes() if path.exists() else None) == previous, f'{path.name} changed during build; not overwritten')
        temporary.chmod(path.stat().st_mode & 0o777 if path.exists() else 0o644)
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            subprocess.run(['gio', 'trash', str(temporary)], check=True)


def write_site(books):
    """Stage only configured books, never the repository or legacy exports."""
    require(any(name == 'index.html' for name, _, _ in books.values()),
            'The Pages site must include a configured index.html')
    site = ROOT / '_site'
    require(not site.exists() and not site.is_symlink(),
            '_site already exists; move it aside or use gio trash _site before rebuilding')
    site.mkdir()
    for name, data, _ in books.values():
        atomic_write(site / name, data, None)
    atomic_write(site / '.nojekyll', b'', None)
    print(f'Staged {len(books)} book(s) in _site/; nothing deployed')


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--lang', help='Build one configured locale; default: all configured locales')
    parser.add_argument('--check', action='store_true', help='Verify generated output without writing it')
    parser.add_argument('--adopt', metavar='SHA256', help='One-time consent to replace a legacy output with this exact hash')
    parser.add_argument('--site', action='store_true', help='Stage all configured books in a new _site/ directory; no deployment')
    args = parser.parse_args(argv)
    require(not args.site or not (args.lang or args.check or args.adopt),
            '--site builds all languages and cannot be combined with --lang, --check or --adopt')
    sources = read_sources(ROOT)
    languages = sorted(Path(name).parent.name for name in sources if re.fullmatch(r'content/[^/]+/book\.yaml', name))
    require(languages, 'No configured books')
    if args.lang:
        require(args.lang in languages, f'Unknown language {args.lang}; configured: {", ".join(languages)}')
    names = [book_config(lang, sources)['output'] for lang in languages]
    require(len(names) == len(set(names)), 'Languages must not share an output filename')
    selected_languages = [args.lang] if args.lang else languages
    outputs = {lang: book_config(lang, sources)['output'] for lang in selected_languages}
    selected = {lang: render_book(lang, sources, outputs) for lang in selected_languages}
    if args.site:
        require(read_sources(ROOT) == sources, 'Sources changed during build; run again')
        write_site(selected)
        return 0
    pending = []
    for lang, (name, data, count) in selected.items():
        path = ROOT / name
        old = path.read_bytes() if path.exists() else None
        if old == data:
            print(f'Current: {name} ({lang}, {count} lessons)')
            continue
        if not args.check:
            require(old is None or is_generated(old) or digest(old) == args.adopt,
                    f'{name} is legacy or manually edited; not overwritten. Reconcile it with the sources first.')
        pending.append((path, data, old))
        print(f'{"Stale" if args.check else "Build"}: {name} ({lang}, {count} lessons, {len(data)} bytes)')
    if args.check:
        return int(bool(pending))
    require(read_sources(ROOT) == sources, 'Sources changed during build; run again')
    for path, data, old in pending:
        atomic_write(path, data, old)
    return 0


if __name__ == '__main__':
    try:
        raise SystemExit(main())
    except (ValueError, KeyError, OSError, yaml.YAMLError, TemplateError) as error:
        raise SystemExit(f'Build refused: {error}') from None
